### ISSUE TITLE
Build on Windows fail

### ISSUE THREAD

**Issue by OTL** [Eljay/assimp-sys#16]
I can't build on windows. Could you help?
```
C:\Users\ogura\rust\assimp-sys>cargo build
   Compiling assimp-sys v0.3.0 (file:///C:/Users/ogura/rust/assimp-sys)
error: failed to run custom build command for `assimp-sys v0.3.0 (file:///C:/Users/ogura/rust/assimp-sys)`
process didn't exit successfully: `C:\Users\ogura\rust\assimp-sys\target\debug\build\assimp-sys-7b7fc934d1f1ac6e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\ogura\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.26\src\lib.rs:599:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   6: cmake::fail
             at C:\Users\ogura\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.26\src\lib.rs:599
   7: cmake::run
             at C:\Users\ogura\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.26\src\lib.rs:580
   8: cmake::Config::build
             at C:\Users\ogura\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.26\src\lib.rs:487
   9: build_script_build::main
             at .\build.rs:15
  10: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  11: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  12: main
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  14: BaseThreadInitThunk
```

**Comment by Eljay** [comment]
Hi, that log doesn't really provide much information. Can you post the build script output from target/debug/build/assimp-sys-xxxxxxxxxxxxxxxx/output to see if it contains any more information?

**Comment by OTL** [comment]
Thank you for response!
It contains .exe and .pdb only.
Is there something I can?

```
 C:\Users\ogura\rust\assimp-sys\target\debug\build\assimp-sys-7b7fc934d1f1ac6e のディレクトリ
2017/10/21  09:40    <DIR>          .
2017/10/21  09:40    <DIR>          ..
2017/10/21  09:40         1,222,656 build-script-build.exe
2017/10/21  09:40         1,222,656 build_script_build-7b7fc934d1f1ac6e.exe
2017/10/21  09:40         3,321,856 build_script_build-7b7fc934d1f1ac6e.pdb
```

**Comment by Eljay** [comment]
There should be another assimp-sys folder next to that one containing the build output.

**Comment by OTL** [comment]
Yes, but it contains no text output.
Attached all of assimp-sys/target/debug/build/

[assimp_build_all.tar.gz](https://github.com/Eljay/assimp-sys/files/1403983/assimp_build_all.tar.gz)

**Comment by Eljay** [comment]
Hmm, I can't see any obvious issues. Can you try to build [assimp](https://github.com/assimp/assimp) by itself and see if that gives any errors.

**Comment by OTL** [comment]
I succeeded to build `assim-sys` finally with small modification.

I needed to add `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin` to PATH env in my environment.

And set `ASSIMP_BUILD_MMD_IMPORTER` because it causes some errors.

Thank you for your kindness.

If you don't mind, how about turning `ASSIMP_BUILD_MMD_IMPORTER` OFF at least on windows?

**Comment by OTL** [comment]
I uploaded #18 .

**Comment by OTL** [comment]
Finally, I found what is the problem.
That is caused by Japanese comment in the MMD library.

This is already fixed in the master branch of assimp as below, but it is not released yet.

https://github.com/assimp/assimp/commit/6a3b030094481c3a901fbc8f570bf889246c9e09

#19 will update the submodule and solve this problem, if you can accept.
